### ISSUE TITLE
Always On Not Working

### ISSUE THREAD

**Issue by Guerte** [OliverHofkens/scryfall-telegram-rs-serverless#13]
Always on mode isn’t returning any queries for my. I’ve added the scryfall bot to my chat and when I tag the bot it works, but brackets don’t.

**Comment by OliverHofkens** [comment]
Hey @Guerte,
in order for the bot to see messages without being  `@`mentioned, it needs to have admin permissions.
Note that the bot can then see ALL messages in that chat, but that's just how Telegram works... 
I promise that I can't access your data or chats whatsoever.

So can you ensure that the bot is an admin in the chat, and try again?

Related: #2

**Comment by OliverHofkens** [comment]
I noticed that this wasn't clear from the README, so I've added a note about this!
