### ISSUE TITLE
Feature request: Fetch prices

### ISSUE THREAD

**Issue by Hexogenx** [OliverHofkens/scryfall-telegram-rs-serverless#14]
Hey, thanks for the bot, my playgroup really likes it.

There are a few people in my group that are also interested in the economy of magic cards, and we've been using the Scryfall Slackbot until now to fetch for card prices.

On behalf of those who like to deal in magic currency, could it be possible to add an option to fetch cardprices from scryfall?
Something like [[$cardname]]

**Comment by OliverHofkens** [comment]
Hey, thanks for the nice words!

This is a great suggestion. Given that the price information is included on Scryfall already, this probably isn't too much work.
I'll check it out soon!

**Comment by OliverHofkens** [comment]
@Hexogenx I've implemented a first version of this, which is now live on the Beta bot (https://t.me/ScryfallBetaBot).
It works as you suggested: just add a dollar or euro sign as the first character between the brackets. The bot will include the prices in the image caption (works for both single card results or galleries with multiple cards).

If no major bugs come out of this, I'll deploy it on the main bot tomorrow!

Some examples:
Single cards, optionally including set specifier:
![Screenshot 2021-09-12 at 17 59 03](https://user-images.githubusercontent.com/23633993/132994504-4e016ca2-c707-40fc-ba1d-a90b11068f0d.png)

Card galleries, prices are shown on select:
![Screenshot 2021-09-12 at 18 00 56](https://user-images.githubusercontent.com/23633993/132994577-5a4a6e90-577a-4a60-983b-39b4457da480.png)
![Screenshot 2021-09-12 at 18 01 10](https://user-images.githubusercontent.com/23633993/132994582-09e5b1fa-3681-4a7d-aca5-86c048fbac33.png)

**Comment by OliverHofkens** [comment]
This is now live 🚀
