### ISSUE TITLE
Support for Telegram topic

### ISSUE THREAD

**Issue by ShadowTemplate** [OliverHofkens/scryfall-telegram-rs-serverless#21]
In the [November 2022 update](https://telegram.org/blog/topics-in-groups-collectible-usernames), Telegram has introduced topics for groups.
If the Scryfall bot is used in a topic, the response with the preview of the card is sent in the general topic.
It would be nice if the bot would be able to reply in the topic chat, as you would naturally expect to happen.

**Comment by OliverHofkens** [comment]
Hey, thanks for reporting this!
I hadn't used topics yet, so never noticed this weird behavior. 
Judging from Telegram's documentation, this is as simple as passing on the `message_thread_id` through when replying. Sounds easy enough, I'll try to fix it this weekend 👍

**Comment by ShadowTemplate** [comment]
Thank you very much!
It will help a lot in large Telegram groups using topics to discuss different sets or categories of cards!
Really appreciated!

**Comment by OliverHofkens** [comment]
This is now live on the Beta Bot for testing (https://t.me/ScryfallBetaBot), but seems to work fine at first glance 👍 
If all goes well, I'll push it to the main bot later today.

**Comment by ShadowTemplate** [comment]
Just tried that and it seems to be working fine!
Thank you so much for the quick fix.
Have an amazing weekend.

**Comment by ShadowTemplate** [comment]
Closing the issue!

**Comment by OliverHofkens** [comment]
This should be live on the main bot now 🚀 
Thanks for the kind words, hope you enjoy your weekend too!
