### ISSUE TITLE
Cannot find "Fae of Wishes"

### ISSUE THREAD

**Issue by tinyau** [OliverHofkens/scryfall-telegram-rs-serverless#3]
For Telegram bot t.me/ScryfallBot - Use "Fae of Wishes" in both inline and always-on mode to search but no result found. 

However, I can search it in https://scryfall.com using "Fae of Wishes".

Please fix the problem, thanks.

**Comment by OliverHofkens** [comment]
I'm sorry, for some reason I didn't get notified about this issue.
I just tested, and at the moment the card is found in both modes. I'm guessing it was a network problem with the bot or something.

If the problem persists on your end, I'll dig a bit deeper. If not, we'll close this issue.
