### ISSUE TITLE
Feature request: Support set syntax in active mode

### ISSUE THREAD

**Issue by henges** [OliverHofkens/scryfall-telegram-rs-serverless#5]
Allow a user to search for an image of a specific edition of a card in active mode by using the 3-letter set abbreviation.
For instance, typing [[Bottle Gnomes]] will still send me an image of that card's most [recent printing](https://scryfall.com/card/cm2/177/bottle-gnomes), while typing [[Bottle Gnomes|TMP]] will send me an image of its [older printing](https://scryfall.com/card/tmp/278/bottle-gnomes) from Tempest.

**Comment by OliverHofkens** [comment]
Great suggestion! I implemented it in #7 . 
I also set up a beta version of the bot where we can test new features like this: [t.me/ScryfallBetaBot](https://t.me/ScryfallBetaBot)
We can test the feature there, and I'll push it to the main bot if everything seems fine!

![Screenshot 2020-08-16 at 17 11 06](https://user-images.githubusercontent.com/23633993/90337552-7b742180-dfe3-11ea-927d-8fdfe513a79e.png)

**Comment by OliverHofkens** [comment]
This is live now! 🚀
