### ISSUE TITLE
Double-faced cards always return Frontside

### ISSUE THREAD

**Issue by suroh1994** [OliverHofkens/scryfall-telegram-rs-serverless#9]
With Zendikar Rising we are getting new double-faced cards. This led to me trying to show a friend both sides of a card by sending a message like "[[Frontside card name]] and [[Backside card name]]". However, this message results in the bot returning the frontside twice. 

After a couple of tests, I can say this happens with old cards as well ("[[Delver of Secrets]] and [[Insectile Aberration]]" returns Delver of Secrets twice). Is there any way you can detect, if a cardname is the backside of a card and return that image instead?

**Comment by OliverHofkens** [comment]
Good suggestion! 
It seems the Scryfall API returns `card_faces` for double-faced cards, we can check on that property to show the relevant image. I'll add this feature soon!

**Comment by OliverHofkens** [comment]
Thanks again for this request! This functionality is now in testing on the beta bot [(ScryfallBetaBot)](https://t.me/ScryfallBetaBot):

![Screenshot 2020-09-06 at 15 31 46](https://user-images.githubusercontent.com/23633993/92326956-4ee97d80-f056-11ea-9628-68890fdad851.png)

**Comment by suroh1994** [comment]
Looks great, thanks for the quick implementation!

**Comment by OliverHofkens** [comment]
My pleasure! This is now live 🚀
